const DEFAULT = {
    tasVersion: "2.3.0",
    preRenderAlgorithm: "high",
    deduplicate: false,
    restore: false,
    upscale: false,
    interpolate: false,
    sharpening: false,
    rifeensemble: false,
    offlineMode: false,
    segmentMethod: "anime",
    deduplicateMethod: "ssim",
    encodeAlgorithm: "x264",
    restoreModel: "anime1080fixer",
    upscaleModel: "shufflecugan",
    interpolationModel: "rife4.6",
    depthModel: "og_distill_small_v2",
    deduplicateSensitivity: 0.5,
    depthQuality: "high",
    sharpeningSensitivity: 0.5,
    autoCutSensitivity: 0.5,
    youtubeUrl: "",
    interpolateFactor: "2",
    isProcessing: false,
    isBackendAvailable: false,
    progressBarValue: 0,
    latestVersion: "unknown",
    bitDepth: "8bit",
    downloadProgress: 0,
    isDownloading: false,
    progressBarState: "indeterminate",
    showDownloadDialog: false,
    CurrentVersionOfExe: "Not Available",
    TASFULLORLITE: "FULL",
    enablePreview: false,
    deletePreRender: false,
    canIShowUpdateDialog: true,
    adjustmentLayerLength: "1",
    solidLayerLength: "1",
    solidLayerColor: "#000000",
    sortLayerMethod: "topDown",
    dynamicScale: false,
    forceStatic: false,
    disableDonatePopup: false,
    nullLayerLength: "1",
    tabListOrientation: "horizontal",
    toolboxLayerLength: "1",
    interpolationFactorList: [
        { name: "2x", value: "2" },
        { name: `2.5x`, value: "2.5" },
        { name: "3x", value: "3" },
        { name: "4x", value: "4" },
        { name: "5x", value: "5" },
        { name: "6x", value: "6" },
        { name: "8x", value: "8" },
        { name: "16x", value: "16" },
        { name: "32x", value: "32" },
        { name: "64x", value: "64" },
    ],
    resize: false,
    resizeFactor: "2",
    uiScale: "medium",
    aiPrecision: "true",
};

export default DEFAULT;
